name: notacookbook
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+4
  google_mlkit_image_labeling: ^0.13.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/foods.tflite
     - assets/images/breakfast.jpg
     - assets/images/dinner.jpg
     - assets/images/dessert.jpg
     - assets/images/food_recognition.jpg
