import 'package:flutter/material.dart';
import 'package:notacookbook/features/recipe_model.dart';

List<Recipe> recipes = [
  Recipe(
    title: "Apple Pie",
    type: "Dessert",
    ingredients: [
      "2 1/2 cups all-purpose flour",
      "1 cup unsalted butter",
      "1/4 cup ice water",
      "6 medium apples",
      "3/4 cup sugar",
      "1 tsp cinnamon",
      "1/4 tsp nutmeg",
      "1 tbsp lemon juice",
      "1 tbsp cornstarch"
    ],
    totaltime: "1 hours",
    servings: 5,
    image: "assets/images/apple_pie.jpg",
    steps: [
      {"Prepare pie crust by mixing flour, butter, and water": 20},
      {"Chill the dough in the refrigerator": 30},
      {"Peel, core, and slice apples": 10},
      {"Mix apples with sugar, spices, lemon juice, and cornstarch": 5},
      {"Roll out dough and line pie dish": 10},
      {"Add apple filling and cover with top crust": 10},
      {"Bake in a preheated oven at 375°F (190°C)": 50},
    ],
  ),
  Recipe(
    title: "Baklava",
    type: "Dessert",
    ingredients: [
      "1 package phyllo dough",
      "2 cups chopped walnuts",
      "1 cup melted butter",
      "1 tsp cinnamon",
      "1 cup sugar",
      "1/2 cup water",
      "1/4 cup honey",
      "1 tsp vanilla extract",
      "1/2 lemon (juice)"
    ],
    totaltime: "1 hours",
    servings: 5,
    image: "assets/images/baklava.jpg",
    steps: [
      {"Preheat oven to 350°F (175°C)": 5},
      {"Layer phyllo dough with butter in a baking dish": 15},
      {"Mix walnuts with cinnamon and sprinkle between layers": 10},
      {"Cut into diamond shapes before baking": 5},
      {"Bake until golden brown": 50},
      {"Prepare syrup with sugar, water, honey, and lemon juice": 10},
      {"Pour cooled syrup over hot baklava": 5},
    ],
  ),
   Recipe(
    title: "Breakfast burrito",
    type: "Main Course",
    ingredients: [

     " 1 large avocado, peeled, pitted, and diced",
"½ cup diced seeded tomatoes, from 1 to 2 tomatoes",
"1 small shallot, minced (about 2 tablespoons)",
"1 clove garlic, minced",
"1 jalapeño pepper, seeded and minced",
"1 tablespoon fresh lime juice, from 1 lime",
"½ teaspoon salt",
"¼ teaspoon ground cumin",
"¼ cup fresh chopped cilantro",
"4 large eggs",
"¼ teaspoon smoked paprika",
"¼ teaspoon salt"
"½ lb spicy sausage (such as chorizo, Italian, or anything you like), removed from casings",
"1⅓ cups (6 oz) shredded Monterey Jack cheese",
'4 (10-in) burrito-size flour tortillas',
"Vegetable oil"
     
    ],
    totaltime: "40 Minutes",
    servings: 4,
    image: "assets/images/burito.jpg",
    steps: [
      {"Make the Avocado-Tomato Salsa: Place all of the ingredients in a medium bowl and mix to combine. Set aside.": 1},   
       {"In a medium bowl, whisk the eggs with the smoked paprika and salt. Set aside.": 2}, 
       {"Heat a large nonstick pan over medium-high heat. Add the sausage and cook, stirring frequently, until browned, 4 to 5 minutes. Use a slotted spoon to transfer the sausage from the pan to a plate, leaving the drippings in the pan. Reduce the heat to low. Add the eggs and scramble until just cooked through. Transfer the eggs to a plate. Clean the pan (you'll use it again).": 3}, 
                 {"Assemble the burritos: Spoon about ¼ cup of the avocado-salsa onto each tortilla (you'll have a little leftover salsa; that's for the cook!), followed by a quarter of the sausage, a quarter of the eggs, and ⅓ cup cheese. Fold in the sides of the tortilla over the filling and roll, tucking in the edges as you go.": 4}, 
                      {"Lightly coat the pan with oil and set over medium heat. When the pan is hot, add the burritos, seam side down. Cook, covered, until the bottom of the burritos are golden brown, about 3 minutes. Flip the burritos over and continue cooking, covered, until golden, a few minutes more. Serve warm.": 5}, 
                          
    ],
  ),
  Recipe(
  title: "Caesar Salad",
  type: "Salad",
  ingredients: [
    "1/2 French Baguette, cut in half and thinly sliced (1/4\" thick)",
    "3 Tbsp extra virgin olive oil",
    "1 tsp minced garlic, 2 small cloves",
    "2 Tbsp grated parmesan cheese",
    "2 small garlic cloves, minced (1 tsp)",
    "2 tsp dijon mustard",
    "1 tsp Worcestershire sauce",
    "2 tsp fresh lemon juice",
    "1 1/2 tsp red wine vinegar",
    "1/3 cup extra virgin olive oil",
    "1/2 tsp sea salt, or to taste",
    "1/8 tsp black pepper, plus more to serve",
    "1 large romaine lettuce, (or 2 small heads romaine)",
    "1/3 cup parmesan cheese, shredded or shaved"
  ],
  image: "assets/images/caesar_salad.jpg", 
  steps: [
    {"Preheat oven to 350˚F": 1},
    {"Cut baguette and place on baking sheet": 2},
    {"Mix olive oil and garlic, drizzle over bread": 3},
    {"Sprinkle with parmesan, toss and bake for 10-12 minutes": 4},
    {"Whisk together garlic, dijon, Worcestershire, lemon juice, and vinegar": 5},
    {"Slowly drizzle in olive oil while whisking": 6},
    {"Whisk in salt and pepper to taste": 7},
    {"Chop romaine and place in a serving bowl": 8},
    {"Sprinkle with parmesan and croutons": 9},
    {"Drizzle with dressing and toss gently": 10}
  ],
  servings: 4,
  totaltime: "30 minutes",
),
    Recipe(
      title: "Caprese Salad",
      type: "Salad",
      ingredients: ["Tomato", "Mozzarella", "Basil", "Olive oil", "Balsamic vinegar"],
      image: "assets/images/caprese_salad.jpg",
      steps: [
        {"Slice tomatoes": 1},
        {"Slice mozzarella": 1},
        {"Layer with basil": 1},
        {"Drizzle with olive oil and balsamic vinegar": 1},
      ],
      servings: 2,
      totaltime: "15 minutes",
    ),
    Recipe(
      title: "Cheesecake",
      type: "Dessert",
      ingredients: ["Cream cheese", "Sugar", "Eggs", "Vanilla", "Graham crackers", "Butter"],
      image: "assets/images/cheesecake.jpg",
      steps: [
        {"Preheat oven": 1},
        {"Prepare crust": 2},
        {"Mix cream cheese filling": 3},
        {"Bake and chill": 4},
      ],
      servings: 8,
      totaltime: "3 hours",
    ),
    Recipe(
      title: "Curry",
      type: "Main Course",
      ingredients: ["Chicken", "Curry paste", "Coconut milk", "Onions", "Garlic", "Ginger", "Vegetables"],
      image: "assets/images/curry.jpg",
      steps: [
        {"Fry onions, garlic, and ginger": 1},
        {"Add chicken and curry paste": 2},
        {"Pour in coconut milk and simmer": 3},
        {"Add vegetables and cook until tender": 4},
      ],
      servings: 4,
      totaltime: "45 minutes",
    ),
    Recipe(
      title: "Chicken Wings",
      type: "Appetizer",
      ingredients: ["Chicken wings", "Hot sauce", "Honey", "Garlic", "Butter"],
      image: "assets/images/chicken_wings.jpg",
      steps: [
        {"Preheat oven": 1},
        {"Coat wings in sauce mixture": 2},
        {"Bake wings until crispy": 3},
      ],
      servings: 2,
      totaltime: "40 minutes",
    ),
    Recipe(
      title: "Chocolate Cake",
      type: "Dessert",
      ingredients: ["Cocoa powder", "Flour", "Sugar", "Eggs", "Butter", "Vanilla", "Milk", "Baking powder"],
      image: "assets/images/chocolate_cake.jpg",
      steps: [
        {"Preheat oven": 1},
        {"Mix dry ingredients": 2},
        {"Add wet ingredients and mix": 3},
        {"Bake for 25 minutes": 4},
      ],
      servings: 10,
      totaltime: "1 hour",
    ),
    Recipe(
      title: "Sandwich",
      type: "Snack",
      ingredients: ["Bread", "Lettuce", "Tomato", "Cheese", "Turkey or Ham", "Mayo"],
      image: "assets/images/sandwich.jpg",
      steps: [
        {"Lay down bread slices": 1},
        {"Add mayo and layer ingredients": 2},
        {"Top with another bread slice": 3},
      ],
      servings: 1,
      totaltime: "5 minutes",
    ),
    Recipe(
      title: "Dumplings",
      type: "Appetizer",
      ingredients: ["Dumpling wrappers", "Ground pork", "Ginger", "Garlic", "Soy sauce", "Spring onions"],
      image: "assets/images/dumplings.jpg",
      steps: [
        {"Mix filling ingredients": 1},
        {"Wrap filling in dumpling wrappers": 2},
        {"Steam or pan-fry dumplings": 3},
      ],
      servings: 4,
      totaltime: "30 minutes",
    ),
    Recipe(
      title: "Fish and Chips",
      type: "Main Course",
      ingredients: ["Fish fillets", "Potatoes", "Flour", "Beer", "Salt", "Pepper", "Oil"],
      image: "assets/images/fish_and_chips.jpg",
      steps: [
        {"Peel and cut potatoes": 1},
        {"Prepare batter for fish": 2},
        {"Fry fish and chips until crispy": 3},
      ],
      servings: 4,
      totaltime: "45 minutes",
    ),
    Recipe(
      title: "French Fries",
      type: "Side",
      ingredients: ["Potatoes", "Oil", "Salt"],
      image: "assets/images/french_fries.jpg",
      steps: [
        {"Peel and cut potatoes": 1},
        {"Heat oil and fry potatoes": 2},
        {"Drain and season with salt": 3},
      ],
      servings: 2,
      totaltime: "30 minutes",
    ),
    Recipe(
      title: "Grilled Cheese Sandwich",
      type: "Snack",
      ingredients: ["Bread", "Cheese", "Butter"],
      image: "assets/images/grilled_cheese.jpg",
      steps: [
        {"Butter bread slices": 1},
        {"Place cheese between bread slices": 2},
        {"Grill on both sides until golden brown": 3},
      ],
      servings: 1,
      totaltime: "10 minutes",
    ),
    Recipe(
      title: "Burger",
      type: "Main Course",
      ingredients: ["Ground beef", "Buns", "Lettuce", "Tomato", "Cheese", "Ketchup", "Mustard"],
      image: "assets/images/burger.jpg",
      steps: [
        {"Form beef patties": 1},
        {"Grill patties and assemble burger": 2},
        {"Add toppings and serve": 3},
      ],
      servings: 2,
      totaltime: "30 minutes",
    ),
    Recipe(
      title: "Hot Dog",
      type: "Snack",
      ingredients: ["Hot dog sausages", "Buns", "Ketchup", "Mustard", "Onions"],
      image: "assets/images/hot_dog.jpg",
      steps: [
        {"Grill sausages": 1},
        {"Place in buns and add toppings": 2},
      ],
      servings: 2,
      totaltime: "15 minutes",
    ),
    Recipe(
      title: "Mac and Cheese",
      type: "Main Course",
      ingredients: ["Pasta", "Cheese", "Milk", "Butter", "Flour"],
      image: "assets/images/mac_and_cheese.jpg",
      steps: [
        {"Cook pasta": 1},
        {"Make cheese sauce": 2},
        {"Mix pasta with sauce": 3},
      ],
      servings: 4,
      totaltime: "30 minutes",
    ),
    Recipe(
      title: "Donuts",
      type: "Dessert",
      ingredients: ["Flour", "Sugar", "Eggs", "Milk", "Butter", "Baking powder", "Oil"],
      image: "assets/images/donuts.jpg",
      steps: [
        {"Mix ingredients and form dough": 1},
        {"Fry donuts in oil": 2},
        {"Coat with sugar and serve": 3},
      ],
      servings: 12,
      totaltime: "1 hour",
    ),
    Recipe(
      title: "Fried Rice",
      type: "Main Course",
      ingredients: ["Rice", "Eggs", "Vegetables", "Soy sauce", "Garlic", "Onions"],
      image: "assets/images/fried_rice.jpg",
      steps: [
        {"Fry garlic and onions": 1},
        {"Add rice and veggies, stir-fry": 2},
        {"Scramble eggs and mix in": 3},
      ],
      servings: 4,
      totaltime: "30 minutes",
    ),
    Recipe(
      title: "Omelette",
      type: "Breakfast",
      ingredients: ["Eggs", "Cheese", "Onions", "Tomatoes", "Mushrooms"],
      image: "assets/images/omelette.jpg",
      steps: [
        {"Whisk eggs": 1},
        {"Cook eggs with fillings": 2},
        {"Fold and serve": 3},
      ],
      servings: 1,
      totaltime: "10 minutes",
    ),
    Recipe(
      title: "Pizza",
      type: "Main Course",
      ingredients: ["Pizza dough", "Tomato sauce", "Cheese", "Toppings of choice"],
      image: "assets/images/pizza.jpg",
      steps: [
        {"Preheat oven": 1},
        {"Spread sauce and cheese on dough": 2},
        {"Bake until crispy": 3},
      ],
      servings: 2,
      totaltime: "40 minutes",
    ),
    Recipe(
      title: "Spaghetti Bolognese",
      type: "Main Course",
      ingredients: ["Spaghetti", "Ground beef", "Tomato sauce", "Garlic", "Onions", "Herbs"],
      image: "assets/images/spaghetti_bolognese.jpg",
      steps: [
        {"Cook spaghetti": 1},
        {"Make bolognese sauce": 2},
        {"Serve sauce over spaghetti": 3},
      ],
      servings: 4,
      totaltime: "45 minutes",
    ),
    Recipe(
      title: "Spaghetti Carbonara",
      type: "Main Course",
      ingredients: ["Spaghetti", "Bacon", "Eggs", "Cheese", "Garlic", "Cream"],
      image: "assets/images/spaghetti_carbonara.jpeg",
      steps: [
        {"Cook spaghetti and bacon": 1},
        {"Mix eggs, cheese, and cream": 2},
        {"Toss spaghetti with sauce": 3},
      ],
      servings: 4,
      totaltime: "30 minutes",
    ),
];
